### ISSUE TITLE
[Issue]: Composition in the schema

### ISSUE THREAD

**Issue by luke-ncc** [National-Composites-Centre/CompoST#7]
### Describe the project you are working on

A simple CompoSt visualisation tool. This tool can be used to view surfaces, splines, and ply edges and cross-sections.

### Describe the issue you have come across

The current schema defines each object structure in isolation, instead of leveraging object composition. This causes the structure to be bloated 

### What features of the format does this affect?

For example, the start of the definition of CompositeElement:
```json
   "CompositeElement": {
          "properties": {
              "memberName": {
                  "anyOf": [
                      {
                          "type": "string"
                      },
                      {
                          "type": "null"
                      }
                  ],
                  "default": null,
                  "title": "Membername"
              },
```
And the start of the definition of Ply, which should be part of the composition of CompositeElement,

```json
 "Ply": {
          "properties": {
              "memberName": {
                  "anyOf": [
                      {
                          "type": "string"
                      },
                      {
                          "type": "null"
                      }
                  ],
                  "default": null,
                  "title": "Membername"
              },
```
This could be simplified by only defining ply with properties specific to that object: 
```json
 "Ply": {
          "properties": {
              
              "material": {
                  "anyOf": [
                      {
                          "type": "string"
                      },
                      {
                          "type": "null"
                      }
                  ],
                  "default": null,
                  "title": "Material"
              },
              "orientation": {
                  "anyOf": [
                      {
                          "type": "number"
                      },
                      {
                          "type": "null"
                      }
                  ],
                  "default": null,
                  "title": "Orientation"
              },
              "splineRelimitationRef": {
                  "anyOf": [
                      {
                          "type": "integer"
                      },
                      {
                          "type": "null"
                      }
                  ],
                  "default": null,
                  "title": "Splinerelimitationref"
              }
          },
          "title": "Ply",
          "type": "object"
}
```
And then using composition by adding a property to the definition:
```json
"allOf": [
    {
        "$ref": "#/$defs/CompositeElement"
    },
    {
     "Definition of a ply goes here": ""
    }
]
```

### Version

v0.67

**Comment by JKucera-NCC** [comment]
Not entirely sure I understand the problem fully, but the following should hopefully cover it:

1. Same properties can be defined for Sequence and Ply, even though ply can be part of Sequence. This is to give flexibility to the user to either use Sequence object, or to simply use plies. The intention is that the smallest aspect can supersedes any previous definitions. That way user can define material for the full sequence, but if one ply deviates this specific ply can have different material attached. (I will add explanation of this logic to documentation shortly). 

2. Some objects can be saved in multiple places. For instance defects can be saved under allDefects, or directly under ply. This is again to allow for flexibility. However, for robustness users can reference the object stored in the other storage location, utilizing object definition and reducing bloat in memory. Then when side is changed during handling, the mirror in the other location should also be automatically adjusted. 

3. Some bloat is currently generated by empty objects being stored. This is to be addressed soon by allowing for cleaning script. However, some testing still has to be done to prevent the cleaning script from affecting functionality (specifically serialization and deserialization)
