### ISSUE TITLE
[Feature]: Explicit ordering of plies

### ISSUE THREAD

**Issue by luke-ncc** [National-Composites-Centre/CompoST#9]
### Describe the project you are working on

A simple CompoSt visualisation tool. This tool can be used to view surfaces, splines, and ply edges and cross-sections.

### Describe what the format is lacking that you need in your project

The current format does not define an order in which plies are layered onto a surface. This means any rendering of plies as layers has to include assumed order of plies, which leads to inconsistency.

### State what specific feature could be added for what you need to represent

The definition of a ply could include the ordering of when it was layered, or some definition in relation to other plies such as the ply it was layered on top of.

### Suggest how the feature could be implemented to support this project as well as future projects that might need this feature

Some PlyOrder feature to define a part-wide ordering of ply layers, or 
a LayedOn feature to define which ply the ply was layered after, with a consideration for the definition for the first ply. 

### Can this feature be represented already by combining  other features?

The order can be assumed from the order the plies appear in the file. However, this is not explicit. Also since plies are structured to include some association to splines, layering by order of appearance means all plies of the same spline need to be defined in order in the file.  

### Version

v0.67

**Comment by JKucera-NCC** [comment]
file:///D:/DOCS_clones/CompoST/docs/build/html/Logic.html#variable-duplication

This is currently considered excessive. The logic employed is that the ordering in allComposites objects corresponds to order of plies/cores/sequences starting from tool surface. This is typically the logic used for composite stacking sequence definitions. Adding over-write definition would only cause confusion (I think).

It also allows for easy deletion or replacement of plies (or other composite objects).

**Comment by JKucera-NCC** [comment]
The order of objects corresponds to position in allComposites list, starting from the tool surface. This corresponds to how composites are defined in other software also. This is no clarified in documentation.

Adding a parameter for this purpose would be unnecessary and potentially confusing.
